### ISSUE TITLE
Need Help With PRETRAIN_TYPE=Autoencoder

### ISSUE THREAD

**Issue by bill3code** [zhongkaifu/RNNSharp#30]
Hello!
You wrote:
"You need to train an auto encoder-decoder model by RNNSharp at first, and then use this pretrained model for your task"

But I do not see how to do it.
Finaly what do you mean by "pretrained model is trained by RNNSharp itself"?

**Comment by zhongkaifu** [comment]
Hi @bill3code ,

The previous description may nit clearly, so I updated it to:

\#For 'Autoencoder', the pretrained model is trained by RNNSharp itself.  For sequence-to-sequence task, "Autoencoder" is required, since source sequence needs to be encoded by this model at first, and then target sequence would be generated by decoder.  

So, it means that you need to run RNNSharp to build autoencoder model at first, and then use it as one of input to build decoder model for your sequence-to-sequence task.

**Comment by bill3code** [comment]
Thank you!
