### ISSUE TITLE
Saving better model crash.

### ISSUE THREAD

**Issue by bill3code** [zhongkaifu/RNNSharp#7]
Hello.

info,20.02.2016 21:08:27 [TRACE] In training: log probability = -6539,9872918264
9, cross-entropy = 0,0073893168866162, perplexity = 1,00513502343797
info,20.02.2016 21:08:27
info,20.02.2016 21:08:27 Saving better model into file model.bin...
info,20.02.2016 21:08:27 Saving input2hidden weights...
info,20.02.2016 21:08:28 Saving matrix with VQ 256...
info,20.02.2016 21:10:28 Sorting data set (size: 1707219900)...

Process is terminated due to StackOverflowException.

Process is terminated due to StackOverflowException.
Process is terminated due to StackOverflowException.

![rnn error](https://cloud.githubusercontent.com/assets/17447547/13278864/dc5e6310-dae4-11e5-971a-ea177135f89d.jpg)

Seems an error occurs in AdvUtils.dll

**Comment by bill3code** [comment]
I'm not sure, but the problem seems to be in the method Split Cluster.

**Comment by zhongkaifu** [comment]
Hi,

Yes, this is a bug in AdvUtils.dll. The values of data may be not balanced, so we call SplitCluster so deep, and then stack is overflow.

I have checked-in some new RNNSharp code, and disable model vector quantization by default, so far, this problem has been mitigated, and I will fix this problem in AdvUtils project.

I suggest you to use the latest RNNSharp or its demo package, since I have done lots of performance optimization for encoding, especially for LSTM. Your training will be much faster than before.

**Comment by bill3code** [comment]
Great! 
Thanks for the support.
